# Generated by Django 5.2.12 on 2026-03-10 23:53

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True, verbose_name='external ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='short name')),
                ('tla', models.CharField(blank=True, max_length=3, verbose_name='TLA')),
                ('crest_url', models.URLField(blank=True, verbose_name='crest URL')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='venue')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.IntegerField(unique=True, verbose_name='external ID')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='home score')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='away score')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TIMED', 'Timed'), ('IN_PLAY', 'In Play'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('matchday', models.IntegerField(verbose_name='matchday')),
                ('kickoff', models.DateTimeField(verbose_name='kickoff')),
                ('season', models.CharField(help_text='e.g. 2025', max_length=10, verbose_name='season')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team', verbose_name='away team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team', verbose_name='home team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('season', models.CharField(max_length=10, verbose_name='season')),
                ('position', models.IntegerField(verbose_name='position')),
                ('played', models.IntegerField(default=0, verbose_name='played')),
                ('won', models.IntegerField(default=0, verbose_name='won')),
                ('drawn', models.IntegerField(default=0, verbose_name='drawn')),
                ('lost', models.IntegerField(default=0, verbose_name='lost')),
                ('goals_for', models.IntegerField(default=0, verbose_name='goals for')),
                ('goals_against', models.IntegerField(default=0, verbose_name='goals against')),
                ('goal_difference', models.IntegerField(default=0, verbose_name='goal difference')),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.team', verbose_name='team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('team', 'season')},
            },
        ),
    ]
