# Generated by Django 5.2.12 on 2026-03-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2h_json', models.JSONField(default=list, verbose_name='H2H matches')),
                ('h2h_summary_json', models.JSONField(default=dict, verbose_name='H2H summary')),
                ('home_form_json', models.JSONField(default=list, verbose_name='home team form')),
                ('away_form_json', models.JSONField(default=list, verbose_name='away team form')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='fetched at')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hype_stats', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'match stats',
                'verbose_name_plural': 'match stats',
            },
        ),
    ]
