# Generated by Django 5.2.12 on 2026-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_add_match_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last attempt at'),
        ),
    ]
