# Generated by Django 5.2.12 on 2026-03-20 22:08

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_last_attempt_at_to_matchstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('body', models.TextField(help_text='Free-form match observations for bot context', verbose_name='notes')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'match notes',
                'verbose_name_plural': 'match notes',
            },
        ),
    ]
