# Generated by Django 5.2.12 on 2026-03-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchnotes',
            name='body',
            field=models.TextField(blank=True, help_text='Free-form match observations for bot context', verbose_name='notes'),
        ),
    ]
