# Generated by Django 5.2.12 on 2026-03-12 00:00

from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                Lower("display_name"),
                condition=Q(display_name__isnull=False) & ~Q(display_name=""),
                name="users_user_display_name_unique_non_empty_ci",
            ),
        ),
    ]
