# Generated by Django 5.2.12 on 2026-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars ($)'), ('GBP', 'UK Pounds (£)'), ('EUR', 'Euros (€)')], default='GBP', max_length=3),
        ),
    ]
