# Generated by Django 5.2.12 on 2026-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_is_bot_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_bg',
            field=models.CharField(default='#374151', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_frame',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_icon',
            field=models.CharField(default='user-circle', max_length=50),
        ),
    ]
