# Generated by Django 5.2.12 on 2026-03-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_avatar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_crest_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
