# Generated by Django 5.2.12 on 2026-03-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_avatar_crest_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_activity_toasts',
            field=models.BooleanField(default=True, help_text='Show live activity feed toasts on every page.'),
        ),
    ]
