# Generated by Django 5.2.12 on 2026-03-16 23:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0003_add_last_attempt_at_to_matchstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomerBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_underdog_threshold', models.DecimalField(decimal_places=2, default=Decimal('3.50'), help_text='Away-win odds at or above this value trigger a DRAW bet instead of AWAY_WIN. Represents the point at which even a homer accepts a draw is the best realistic outcome.', max_digits=5)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homer_bots', to='matches.team')),
                ('user', models.OneToOneField(limit_choices_to={'is_bot': True}, on_delete=django.db.models.deletion.CASCADE, related_name='homer_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homer Bot config',
                'verbose_name_plural': 'Homer Bot configs',
            },
        ),
    ]
