# Generated by Django 5.2.12 on 2026-03-18 04:14

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('discussions', '0001_initial'),
        ('matches', '0003_add_last_attempt_at_to_matchstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('trigger_type', models.CharField(choices=[('PRE_MATCH', 'Pre-match hype'), ('POST_BET', 'Post-bet reaction'), ('POST_MATCH', 'Post-match reaction')], max_length=20, verbose_name='trigger type')),
                ('prompt_used', models.TextField(blank=True, verbose_name='prompt used')),
                ('raw_response', models.TextField(blank=True, verbose_name='raw response')),
                ('filtered', models.BooleanField(default=False, help_text='True if the post-hoc filter rejected this comment.', verbose_name='filtered out')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_comment_meta', to='discussions.comment', verbose_name='posted comment')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_comments', to='matches.match', verbose_name='match')),
                ('user', models.ForeignKey(limit_choices_to={'is_bot': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bot_comments', to=settings.AUTH_USER_MODEL, verbose_name='bot user')),
            ],
            options={
                'verbose_name': 'bot comment',
                'verbose_name_plural': 'bot comments',
                'indexes': [models.Index(fields=['match', 'trigger_type'], name='bots_botcom_match_i_176d82_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'match', 'trigger_type'), name='unique_bot_comment_per_trigger')],
            },
        ),
    ]
