# Generated by Django 5.2.12 on 2026-03-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomerBotConfig',
        ),
    ]
