# Generated by Django 5.2.12 on 2026-03-19 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_drop_homerbotconfig'),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_replies', to='discussions.comment', verbose_name='replied to'),
        ),
        migrations.AlterField(
            model_name='botcomment',
            name='trigger_type',
            field=models.CharField(choices=[('PRE_MATCH', 'Pre-match hype'), ('POST_BET', 'Post-bet reaction'), ('POST_MATCH', 'Post-match reaction'), ('REPLY', 'Reply to comment')], max_length=20, verbose_name='trigger type'),
        ),
    ]
