# Generated by Django 5.2.12 on 2026-03-20 16:53

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_add_reply_trigger_and_parent_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('strategy_type', models.CharField(choices=[('frontrunner', 'Frontrunner'), ('underdog', 'Underdog'), ('parlay', 'Parlay'), ('draw_specialist', 'Draw Specialist'), ('value_hunter', 'Value Hunter'), ('chaos_agent', 'Chaos Agent'), ('all_in_alice', 'All-In Alice'), ('homer', 'Homer (team-loyal)')], max_length=30, verbose_name='strategy type')),
                ('team_tla', models.CharField(blank=True, help_text='Only for homer bots. Must match a Team.tla value.', max_length=5, verbose_name='team TLA')),
                ('persona_prompt', models.TextField(help_text='Full system prompt sent to the LLM. Edit to tweak personality and voice.', verbose_name='persona prompt')),
                ('avatar_icon', models.CharField(default='robot', help_text='Lucide icon name.', max_length=30, verbose_name='avatar icon')),
                ('avatar_bg', models.CharField(default='#374151', help_text='Hex colour for the avatar background.', max_length=10, verbose_name='avatar background')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive bots are skipped by all tasks.', verbose_name='active')),
                ('user', models.OneToOneField(limit_choices_to={'is_bot': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to=settings.AUTH_USER_MODEL, verbose_name='bot user')),
            ],
            options={
                'verbose_name': 'bot profile',
                'verbose_name_plural': 'bot profiles',
            },
        ),
    ]
