# Generated by Django 5.2.12 on 2026-03-10 23:53

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('selection', models.CharField(choices=[('HOME_WIN', 'Home Win'), ('DRAW', 'Draw'), ('AWAY_WIN', 'Away Win')], max_length=10, verbose_name='selection')),
                ('odds_at_placement', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='odds at placement')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stake')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], default='PENDING', max_length=10, verbose_name='status')),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='payout')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='matches.match', verbose_name='match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bookmaker', models.CharField(max_length=100, verbose_name='bookmaker')),
                ('home_win', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='home win')),
                ('draw', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='draw')),
                ('away_win', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='away win')),
                ('fetched_at', models.DateTimeField(verbose_name='fetched at')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='matches.match', verbose_name='match')),
            ],
            options={
                'verbose_name_plural': 'odds',
                'ordering': ['-fetched_at'],
                'unique_together': {('match', 'bookmaker')},
            },
        ),
    ]
