# Generated by Django 5.2.12 on 2026-03-13 18:25

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankruptcy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('balance_at_bankruptcy', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance at bankruptcy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcies', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'bankruptcies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bailout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailouts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('bankruptcy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bailout', to='betting.bankruptcy', verbose_name='bankruptcy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
