# Generated by Django 5.2.12 on 2026-03-15 05:54

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_add_parlay_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total_bets', models.PositiveIntegerField(default=0, verbose_name='total bets')),
                ('total_wins', models.PositiveIntegerField(default=0, verbose_name='total wins')),
                ('total_losses', models.PositiveIntegerField(default=0, verbose_name='total losses')),
                ('total_staked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total staked')),
                ('total_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total payout')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='net profit')),
                ('current_streak', models.IntegerField(default=0, help_text='Positive = win streak, negative = loss streak', verbose_name='current streak')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='best win streak')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'user stats',
            },
        ),
    ]
