# Generated by Django 5.2.12 on 2026-03-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_add_badge_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(help_text='Phosphor icon name', max_length=50, verbose_name='icon'),
        ),
    ]
