# Generated by Django 5.2.12 on 2026-03-17 02:37

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_alter_badge_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance after')),
                ('transaction_type', models.CharField(choices=[('SIGNUP', 'Signup bonus'), ('BET_PLACEMENT', 'Bet placed'), ('BET_WIN', 'Bet won'), ('BET_VOID', 'Bet voided'), ('PARLAY_PLACEMENT', 'Parlay placed'), ('PARLAY_WIN', 'Parlay won'), ('PARLAY_VOID', 'Parlay voided'), ('CHALLENGE_REWARD', 'Challenge reward'), ('REWARD', 'Reward'), ('BAILOUT', 'Bailout'), ('ADMIN_RESET', 'Admin reset')], max_length=20, verbose_name='type')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='betting_bal_user_id_2cdeb2_idx')],
            },
        ),
    ]
