# Generated by Django 5.2.12 on 2026-03-17 02:37

from decimal import Decimal

from django.db import migrations


def backfill_signup_transactions(apps, schema_editor):
    """Create a SIGNUP transaction for every existing user that has a balance."""
    UserBalance = apps.get_model("betting", "UserBalance")
    BalanceTransaction = apps.get_model("betting", "BalanceTransaction")

    balances = UserBalance.objects.select_related("user").all()
    to_create = []
    for ub in balances:
        if not BalanceTransaction.objects.filter(user=ub.user).exists():
            to_create.append(
                BalanceTransaction(
                    user=ub.user,
                    amount=Decimal("1000.00"),
                    balance_after=Decimal("1000.00"),
                    transaction_type="SIGNUP",
                    description="Initial signup bonus",
                )
            )
    created = BalanceTransaction.objects.bulk_create(to_create)

    # Fix created_at to match user's date_joined
    if created:
        from django.db import connection

        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE betting_balancetransaction bt
                SET created_at = u.date_joined
                FROM users_user u
                WHERE bt.user_id = u.id
                  AND bt.transaction_type = 'SIGNUP'
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0007_balancetransaction"),
    ]

    operations = [
        migrations.RunPython(
            backfill_signup_transactions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
