# Generated by Django 5.2.12 on 2026-03-13 01:07

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rule_type', models.CharField(choices=[('BET_COUNT', 'Bet count milestone'), ('STAKE_AMOUNT', 'Stake amount threshold')], max_length=20, verbose_name='rule type')),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Bet count (e.g. 10) or stake amount (e.g. 100.00)', max_digits=10, verbose_name='threshold')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('reward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='rewards.reward', verbose_name='reward')),
            ],
            options={
                'ordering': ['rule_type', 'threshold'],
                'unique_together': {('rule_type', 'threshold')},
            },
        ),
    ]
