# Generated by Django 5.2.12 on 2026-03-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bot_bet', 'Bot Bet'), ('bot_comment', 'Bot Comment'), ('bot_board_post', 'Bot Board Post'), ('score_change', 'Score Change'), ('odds_update', 'Odds Update'), ('bet_settlement', 'Bet Settlement')], max_length=20)),
                ('message', models.CharField(max_length=280)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(default='lightning', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['broadcast_at', 'created_at'], name='activity_pending_broadcast_idx')],
            },
        ),
    ]
