"""
Challenge template definitions for seeding.

Each entry maps to a ChallengeTemplate row. The ``criteria_params`` dict
varies by ``criteria_type`` — see engine.py for evaluation logic.
"""

CHALLENGE_TEMPLATE_DEFINITIONS = [
    # ── Daily challenges (2–3 active at a time, rotated) ─────────────────────
    {
        "slug": "daily_quick_three",
        "title": "Quick Three",
        "description": "Place 3 bets today.",
        "icon": "number-three",
        "challenge_type": "DAILY",
        "criteria_type": "BET_COUNT",
        "criteria_params": {"target": 3},
        "reward_amount": "25.00",
    },
    {
        "slug": "daily_underdog_believer",
        "title": "Underdog Believer",
        "description": "Bet on an underdog with odds greater than 3.00.",
        "icon": "dog",
        "challenge_type": "DAILY",
        "criteria_type": "BET_ON_UNDERDOG",
        "criteria_params": {"target": 1, "odds_min": "3.00"},
        "reward_amount": "35.00",
    },
    {
        "slug": "daily_double_down",
        "title": "Double Down",
        "description": "Place 2 bets on different matches.",
        "icon": "number-two",
        "challenge_type": "DAILY",
        "criteria_type": "BET_COUNT",
        "criteria_params": {"target": 2},
        "reward_amount": "25.00",
    },
    {
        "slug": "daily_high_roller",
        "title": "High Roller",
        "description": "Stake 500 or more credits total today.",
        "icon": "coins",
        "challenge_type": "DAILY",
        "criteria_type": "TOTAL_STAKED",
        "criteria_params": {"target": 500},
        "reward_amount": "50.00",
    },
    {
        "slug": "daily_parlay_builder",
        "title": "Parlay Builder",
        "description": "Place a parlay with at least 2 legs.",
        "icon": "link-simple",
        "challenge_type": "DAILY",
        "criteria_type": "PARLAY_PLACED",
        "criteria_params": {"target": 1, "min_legs": 2},
        "reward_amount": "40.00",
    },
    {
        "slug": "daily_lucky_guess",
        "title": "Lucky Guess",
        "description": "Win any bet today.",
        "icon": "clover",
        "challenge_type": "DAILY",
        "criteria_type": "WIN_COUNT",
        "criteria_params": {"target": 1},
        "reward_amount": "30.00",
    },
    {
        "slug": "daily_triple_threat",
        "title": "Triple Threat",
        "description": "Win 3 bets today.",
        "icon": "fire",
        "challenge_type": "DAILY",
        "criteria_type": "WIN_COUNT",
        "criteria_params": {"target": 3},
        "reward_amount": "50.00",
    },
    {
        "slug": "daily_all_in",
        "title": "All In",
        "description": "Place 5 bets today.",
        "icon": "dice-five",
        "challenge_type": "DAILY",
        "criteria_type": "BET_COUNT",
        "criteria_params": {"target": 5},
        "reward_amount": "40.00",
    },
    {
        "slug": "daily_long_shot",
        "title": "Long Shot",
        "description": "Bet on a long shot with odds greater than 5.00.",
        "icon": "rocket",
        "challenge_type": "DAILY",
        "criteria_type": "BET_ON_UNDERDOG",
        "criteria_params": {"target": 1, "odds_min": "5.00"},
        "reward_amount": "50.00",
    },
    {
        "slug": "daily_parlay_pair",
        "title": "Parlay Pair",
        "description": "Place 2 parlays today.",
        "icon": "target",
        "challenge_type": "DAILY",
        "criteria_type": "PARLAY_PLACED",
        "criteria_params": {"target": 2, "min_legs": 2},
        "reward_amount": "45.00",
    },
    # ── Weekly challenges (2 active at a time, matchweek-aligned) ────────────
    {
        "slug": "weekly_matchweek_maven",
        "title": "Matchweek Maven",
        "description": "Bet on every match this matchweek.",
        "icon": "trophy",
        "challenge_type": "WEEKLY",
        "criteria_type": "BET_ALL_MATCHES",
        "criteria_params": {"target": 10},  # overridden at activation time
        "reward_amount": "200.00",
    },
    {
        "slug": "weekly_streak_chaser",
        "title": "Streak Chaser",
        "description": "Win 4 bets in a row this week.",
        "icon": "lightning",
        "challenge_type": "WEEKLY",
        "criteria_type": "WIN_STREAK",
        "criteria_params": {"target": 4},
        "reward_amount": "250.00",
    },
    {
        "slug": "weekly_sharp_shooter",
        "title": "Sharp Shooter",
        "description": "Correctly predict 5 or more match outcomes this week.",
        "icon": "crosshair",
        "challenge_type": "WEEKLY",
        "criteria_type": "CORRECT_PREDICTIONS",
        "criteria_params": {"target": 5},
        "reward_amount": "200.00",
    },
    {
        "slug": "weekly_parlay_master",
        "title": "Parlay Master",
        "description": "Place 3 parlays this week.",
        "icon": "crown",
        "challenge_type": "WEEKLY",
        "criteria_type": "PARLAY_PLACED",
        "criteria_params": {"target": 3, "min_legs": 2},
        "reward_amount": "150.00",
    },
    {
        "slug": "weekly_underdog_week",
        "title": "Underdog Week",
        "description": "Bet on 3 underdogs (odds > 3.00) this week.",
        "icon": "paw-print",
        "challenge_type": "WEEKLY",
        "criteria_type": "BET_ON_UNDERDOG",
        "criteria_params": {"target": 3, "odds_min": "3.00"},
        "reward_amount": "150.00",
    },
    {
        "slug": "weekly_big_spender",
        "title": "Big Spender",
        "description": "Stake 2,000 or more credits total this week.",
        "icon": "money-wavy",
        "challenge_type": "WEEKLY",
        "criteria_type": "TOTAL_STAKED",
        "criteria_params": {"target": 2000},
        "reward_amount": "200.00",
    },
]
