# Generated by Django 5.2.12 on 2026-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challengetemplate_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetemplate',
            name='criteria_type',
            field=models.CharField(choices=[('BET_COUNT', 'Place N bets'), ('BET_ON_UNDERDOG', 'Bet on underdog'), ('WIN_COUNT', 'Win N bets'), ('WIN_STREAK', 'Win N in a row'), ('PARLAY_PLACED', 'Place a parlay'), ('PARLAY_WON', 'Win a parlay'), ('TOTAL_STAKED', 'Stake N+ total'), ('BET_ALL_MATCHES', 'Bet on every match'), ('CORRECT_PREDICTIONS', 'Predict N+ correct')], max_length=25),
        ),
    ]
