# Generated by Django 5.2.12 on 2026-03-19 15:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hash', models.CharField(default=core.models.generate_short_id, editable=False, help_text='Unique 8-character identifier for client-side use', max_length=8, unique=True, verbose_name='ID Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('post_type', models.CharField(choices=[('results_table', 'Results & Table'), ('prediction', 'Prediction'), ('meta', 'Meta')], max_length=20, verbose_name='post type')),
                ('body', models.TextField(max_length=2000, verbose_name='body')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='hidden')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='board.boardpost', verbose_name='parent post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post_type', 'created_at'], name='board_board_post_ty_7b20ce_idx'), models.Index(fields=['parent'], name='board_board_parent__1fe5ca_idx'), models.Index(fields=['author', 'created_at'], name='board_board_author__5e7755_idx')],
            },
        ),
    ]
